[package]
name = "application"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gpui-kit.workspace = true
project.workspace = true
compositor.workspace = true
renderer.workspace = true
rfd.workspace = true
image.workspace = true
fontdb.workspace = true
cosmic-text.workspace = true
serde_json.workspace = true

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
